guests = ['person','person2','person3']
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print(guests[2] + " couldn't make it to dinner.")
del guests[2]
guests.insert(2, 'person4')
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print("We found a bigger table, time to invite 3 more people!")
guests.insert(0, 'person5')
guests.insert(3, 'person6')
guests.insert(6, 'person7')
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print("Hi " + guests[3] + ", want to come eat dinner with me?")
print("Hi " + guests[4] + ", want to come eat dinner with me?")
print("Hi " + guests[5] + ", want to come eat dinner with me?")