guests = ['person','person2','person3']
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print(guests[2] + " couldn't make it to dinner.")
del guests[2]
guests.insert(2, 'person4')
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print("We found a bigger table, time to invite 3 more people!")
guests.insert(0, 'person5')
guests.insert(3, 'person6')
guests.insert(6, 'person7')
print("Hi " + guests[0] + ", want to come eat dinner with me?")
print("Hi " + guests[1] + ", want to come eat dinner with me?")
print("Hi " + guests[2] + ", want to come eat dinner with me?")
print("Hi " + guests[3] + ", want to come eat dinner with me?")
print("Hi " + guests[4] + ", want to come eat dinner with me?")
print("Hi " + guests[5] + ", want to come eat dinner with me?")
print("new table isn't gonna arrive in time for dinner, so I can only invite 2 people now.")
popped_guest = guests.pop()
print("sorry you couldn't make it to dinner " + popped_guest + ", there just wasn't enough room.")
popped_guest2 = guests.pop()
print("sorry you couldn't make it to dinner " + popped_guest2 + ", there just wasn't enough room.")
popped_guest3 = guests.pop()
print("sorry you couldn't make it to dinner " + popped_guest3 + ", there just wasn't enough room.")
popped_guest4 = guests.pop()
print("sorry you couldn't make it to dinner " + popped_guest4 + ", there just wasn't enough room.")
print("I'm glad that " + guests[0] + " and " + guests[1] + " could make it to dinner.")
del guests[0]
del guests[0]
print(guests)